# 依存パッケージの脆弱性を自動検知し、PRを自動作成する設定。
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
